
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nndcubutitvdvjqbkqlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uZGN1YnV0aXR2ZHZqcWJrcWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDIyMjQsImV4cCI6MjA2MzIxODIyNH0._e3yxvDat6pEpYKKWkxir2fRSUFqvsTVcYgEJDI3h10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
